# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Hasiera
    url: /
    weight: 10
  - name: Gidaliburuak
    url: /gidaliburuak
    weight: 20
  - name: Berriak
    url: /berriak
    weight: 30
  - name: Kontaktua
    url: mailTo:xabi@trikuxabi.eus
    weight: 40
